version: '3.9'

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  api:
    build: .
    container_name: fastapi_app    
    working_dir: /app
    command: python start_server.py uvicorn
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    depends_on:
      - redis
      - celery

  celery:
    build: .
    container_name: celery_worker    
    working_dir: /app
    command: python start_server.py celery
    env_file:
      - .env.docker
    depends_on:
      - redis

  flower:
    build: .
    container_name: flower    
    working_dir: /app
    command: python start_server.py flower
    ports:
      - "5555:5555"
    env_file:
      - .env.docker
    depends_on:
      - redis
      - celery
